feat: revise frontend design
n06ody/stealth-uniswap pull request #2
Opened 2024-03-18 02:57 UTC by QiyuanMa

2024-03-18 04:10 UTC, eleminsoda reviewed
Do we want to note down what this PR has done and how the final output looks like in the description?

2024-03-18 04:10 UTC, eleminsoda commented on uniswap-interface-stealth/src/theme/BackgroundComponent.tsx
> +// import React, { useEffect, useRef, useState, ReactNode } from 'react';
Can we remove the commented codes?

2024-03-19 01:13 UTC, n06ody requested changes

2024-03-19 01:13 UTC, n06ody commented on uniswap-interface-stealth/src/theme/BackgroundComponent.tsx
> +// import React, { useEffect, useRef, useState, ReactNode } from 'react';
+1

2024-03-19 01:13 UTC, n06ody commented on uniswap-interface-stealth/src/theme/index.tsx
> +// 转换十六进制颜色为RGBA格式的函数
Think we can remove these auto-generated comments or replace with something meaningful

2024-03-24 09:26 UTC, merged